# Generated by Django 4.2.23 on 2025-08-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_featured_image_comment_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='featured_image',
        ),
    ]
